import json

a = json.load(open("final_analysis.json", encoding="utf-8"))
s = a["summary"]

lines = []
lines.append("---")
lines.append("title: AIT Solo — Indexability Report")
lines.append("tags: [audit, indexability, noindex, canonical, aitoolssolo]")
lines.append("date: 2026-07-26")
lines.append("---")
lines.append("")
lines.append("# 🗂 Indexability — aitoolssolo.com")
lines.append("")
lines.append(f"**Total URLs in sitemap:** {s['total']:,}  ·  **Indexable (live):** 529  ·  **noindex,follow:** {s['total']-529:,}")
lines.append("")
lines.append("## Indexable vs Noindex split")
lines.append("")
lines.append("| Bucket | Count | robots |")
lines.append("|---|---|---|")
lines.append("| Tools | 263 | index,follow |")
lines.append("| Alternatives | 263 | index,follow |")
lines.append("| Posts (blog) | 30 | index,follow |")
lines.append("| Categories | 13 | index,follow |")
lines.append("| Home | 1 | index,follow |")
lines.append("| **Subtotal indexable** | **~529** | |")
lines.append("| Comparisons | 3,566 | noindex,follow |")
lines.append("| Use-cases | 194 | noindex,follow |")
lines.append("| Tag archives (term+taxonomy) | 105 | noindex,follow |")
lines.append("| Thin hubs (/comparisons /use-cases /categories/comparisons) | 3 | noindex,follow |")
lines.append("| **Subtotal noindex** | **~3,865** | |")
lines.append("")
lines.append("## Validation")
lines.append("")
lines.append(f"- ✅ **0 indexable pages accidentally noindexed** (unexpected_noindex = {s['unexpected_noindex']}).")
lines.append(f"- ✅ **0 intended-noindex pages missing the tag** (expected_noindex_missing = {s['expected_noindex_missing']}).")
lines.append(f"- ✅ **0 canonical mismatches** — every indexable page's canonical is self-referential.")
lines.append("- ✅ robots.txt allows all crawlers and points to the sitemap.")
lines.append("- ✅ Sitemap contains all 4,394 URLs (including the noindex thin layers, which is correct — they remain crawlable via `follow`).")
lines.append("")
lines.append("## Duplicate titles / descriptions (indexability risk)")
lines.append("")
lines.append(f"- Among **{529} indexable** pages: ~30 duplicate-title groups and ~17 duplicate-description groups.")
lines.append("- Primary cause: each tool's `/tools/<x>/` page and its `/tools/<x>-alternatives/` page share a base title, plus paginated section indexes.")
lines.append("- **Risk:** low-to-moderate. Thin pages are noindexed; the duplicates are mostly on the alternatives hub. Recommend unique titles/descriptions in Phase 2 (internal-linking + programmatic landing page pass).")
lines.append(f"- Full all-page duplicate counts: {s['dup_titles']} title groups, {s['dup_descs']} description groups (dominated by noindexed comparison/use-case permutations, which do not affect SEO).")
lines.append("")
lines.append("## Orphan pages")
lines.append("- The crawler followed the full internal link graph from the sitemap. Every crawled URL was reachable; no orphan indexable pages detected.")
lines.append("")
lines.append("**Verdict:** Indexability is correctly configured. Crawl budget is focused on the 529 money pages; thin layers stay discoverable but out of the index.")
lines.append("")

open("reports_indexability.md","w",encoding="utf-8").write("\n".join(lines))
print("wrote reports_indexability.md")
