#!/usr/bin/env python3
"""
Freshness Queue generator for aitoolssolo.com (Hugo/PaperMod).

Scans content/posts/*.md and emits a weekly review queue based on staleness
signals:
  - >90 days since lastmod verification
  - flagged vendors whose pricing/features change often (AI tools)
  - any post whose front-matter lastmod is missing/old

Output: scripts/freshness_queue.md  (markdown, obsidian-friendly)

Run weekly (cron Mondays) BEFORE the GSC KPI pull so the two line up.
"""
import os, re, datetime, glob

ROOT = r"C:\Users\prin-win\aitoolssolo"
POSTS = os.path.join(ROOT, "content", "posts")
OUT = os.path.join(ROOT, "scripts", "freshness_queue.md")

# Vendors whose pricing/features churn fast -> always worth a pricing re-check
HIGH_CHURN = [
    "make.com", "makecom", "riverside", "jasper", "chatgpt", "claude", "descript",
    "beehiiv", "substack", "surfer", "clearscope", "midjourney", "leonardo",
    "krea", "luma", "playground", "canva", "ahrefs", "neuronwriter", "hostinger",
    "clickup", "notion", "miro", "whimsical", "float", "expensify", "brex",
    "square", "quickbooks", "freshbooks", "bonsai", "indy", "vectorizer",
    "browserbear", "relay", "memair", "mem", "stitch", "anima", "lovable",
    "chatpdf", "elicit", "brandwell", "docracy", "legalzoom", "and co",
]

NOW = datetime.date.today()
STALE_DAYS = 90

def parse_frontmatter(text):
    if not text.startswith("---"):
        return {}, ""
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}, ""
    fm = parts[1]
    body = parts[2]
    meta = {}
    for line in fm.splitlines():
        m = re.match(r'^(\w+):\s*(.*)$', line)
        if m:
            meta[m.group(1).strip()] = m.group(2).strip().strip('"').strip("'")
    return meta, body

rows = []
for path in glob.glob(os.path.join(POSTS, "*.md")):
    fn = os.path.basename(path)
    text = open(path, encoding="utf-8").read()
    meta, body = parse_frontmatter(text)
    title = meta.get("title", fn)
    lastmod = meta.get("lastmod") or meta.get("date", "")
    try:
        d = datetime.datetime.fromisoformat(lastmod).date()
    except Exception:
        d = None
    age = (NOW - d).days if d else 9999

    reasons = []
    if age > STALE_DAYS:
        reasons.append(f">90d since lastmod ({age}d)")
    if d is None:
        reasons.append("no lastmod/date")

    low = (title + " " + body[:4000]).lower()
    hits = [v for v in HIGH_CHURN if v in low]
    if hits:
        reasons.append("high-churn vendor(s): " + ", ".join(sorted(set(hits))[:4]))

    # broken affiliate link heuristic: contains aitoolssolo via but no real domain
    if "via=aitoolssolo" in body and ("http" not in body.split("via=aitoolssolo")[0][-40:]):
        reasons.append("check affiliate link live")

    if reasons:
        rows.append({"file": fn, "title": title, "age": age, "reasons": reasons,
                     "path": path})

# Sort: oldest first, then most reasons
rows.sort(key=lambda r: (-len(r["reasons"]), -r["age"]))

lines = []
lines.append(f"---\ntitle: Freshness Queue (auto)\ntags: [freshness, maintenance]\ndate: {NOW.isoformat()}\n---\n")
lines.append(f"# 🔄 Freshness Queue — {NOW.isoformat()}\n")
lines.append(f"**{len(rows)} posts need review.** Generated by `scripts/freshness_queue.py`.\n")
lines.append("\n## Priority review list\n")
for r in rows:
    lines.append(f"- [ ] **{r['title']}** (`{r['file']}`) — {r['age']}d old")
    for why in r["reasons"]:
        lines.append(f"    - {why}")

out = "\n".join(lines) + "\n"
with open(OUT, "w", encoding="utf-8") as f:
    f.write(out)

print(f"Wrote {OUT}")
print(f"{len(rows)} posts in queue.")
for r in rows[:8]:
    print(f"  {r['age']:>5}d  {r['title'][:50]}")
