# Wave 2: ~170 additional curated real tools. Imported by seed_tools.py.
# Each row: (slug, name, cat, summary, pricing, rating, [tags], [feat], [best], [pros], [cons])

T2 = [
  # WRITING & CONTENT
  ("grammarly","Grammarly","writing","AI grammar, spelling, and tone suggestions across every app and site.","Freemium / $12 mo","4.5",["writing","grammar","editing","proofreading"],["Browser + app integration","Tone rewrites","Plagiarism check"],["Everyday writers","Students"],["Ubiquitous","Reliable"],["Paywalls basics"]),
  ("sudowrite","Sudowrite","writing","Fiction-writing AI for novelists: brainstorm, describe, and beat writer's block.","$10-22 mo","4.4",["writing","fiction","creative"],["Story brainstorming","Show-don't-tell rewrites","Character chat"],["Novelists","Fiction authors"],["Tailored to prose","Creative"],["Niche use"]),
  ("copy-ai","Copy.ai","writing","Generative copy for marketing teams - slogans, emails, product blurbs.","Freemium / $36 mo","4.3",["writing","copywriting","marketing"],["50+ templates","Workflows","Brand voice"],["Marketers","Founders"],["Fast drafts","Team features"],["Repetitive output"]),
  ("rytr","Rytr","writing","Low-cost AI writing assistant for short-form content and emails.","Freemium / $9 mo","4.2",["writing","copywriting","affordable"],["30+ use cases","Tone presets","Multilingual"],["Solopreneurs","Freelancers"],["Cheap","Simple"],["Basic long-form"]),
  ("writesonic","Writesonic","writing","AI article writer with SEO mode and chat; includes Botsonic chatbots.","Freemium / $16 mo","4.3",["writing","seo","articles"],["SEO article writer","Chat model","Landing pages"],["SEO bloggers","Agencies"],["SEO focus","Fast"],["Word limits"]),
  ("quillbot","QuillBot","writing","Paraphraser, summarizer, and grammar tools for cleaner writing.","Freemium / $10 mo","4.4",["writing","paraphrasing","summarizing"],["Paraphrase modes","Summarizer","Citation gen"],["Students","Writers"],["Strong paraphraser"],["Free tier limited"]),
  ("hemingway","Hemingway Editor","writing","Highlights dense sentences and readability issues to tighten prose.","One-time $19","4.3",["writing","editing","readability"],["Readability grade","Bold suggestions"],["Bloggers","Editors"],["Improves clarity"],["No AI gen"]),
  ("prowritingaid","ProWritingAid","writing","Deep editing reports for fiction and business writing.","Freemium / $10 mo","4.4",["writing","editing","style"],["20+ writing reports","Integrations"],["Authors","Professionals"],["Thorough","Detailed"],["Busy UI"]),
  ("verb","Verb.ai","writing","AI writing for enterprise comms and knowledge work.","Custom","4.0",["writing","enterprise"],["Workflow writing","Permissions"],["Teams","Enterprise"],["Secure"],["Opaque pricing"]),
  ("wordtune","Wordtune","writing","Rewrite and tone-shift sentences with AI suggestions.","Freemium / $10 mo","4.2",["writing","rewriting","tone"],["Rewrite options","Tone presets"],["Professionals","Writers"],["Natural rewrites"],["Limited free"]),
  ("hyperwrite","HyperWrite","writing","Personal writing assistant with autowrite and summarizer.","Freemium / $20 mo","4.1",["writing","assistant","autocomplete"],["Autowrite","Summarize"],["Writers","Researchers"],["Context-aware"],["Costly"]),
  ("ink-editor","INK Editor","writing","SEO-focused AI writing with built-in optimization scoring.","Freemium / $44 mo","4.0",["writing","seo","content"],["SEO scoring","AI writer"],["SEO writers"],["SEO built-in"],["Pricey"]),
  ("frase","Frase","writing","SEO content briefs and AI writing in one workflow.","$15-45 mo","4.2",["writing","seo","briefs"],["Brief generator","Content AI","SERP analysis"],["SEO agencies"],["Briefs fast"],["Learning curve"]),
  ("surfer-seo","Surfer SEO","writing","On-page SEO optimization with content score and audit.","$59-139 mo","4.4",["writing","seo","optimization"],["Content score","Audit","SERP explorer"],["SEO pros","Agencies"],["Rank-focused"],["Pricey"]),
  ("clearscope","Clearscope","writing","Enterprise content optimization for SEO teams.","~$170 mo","4.3",["writing","seo","enterprise"],["Term recommendations","Reports"],["Enterprise","Agencies"],["Best-in-class SEO"],["Expensive"]),
  ("marketmuse","MarketMuse","writing","AI content planning and briefs for topic authority.","Custom","4.1",["writing","seo","planning"],["Content inventory","Briefs"],["Enterprise"],["Strategic"],["Costly"]),
  ("anyword","Anyword","writing","Performance-predictive copywriting with conversion scores.","$39-99 mo","4.2",["writing","copywriting","analytics"],["Predictive scores","Templates"],["Marketers"],["Data-driven"],["Niche"]),
  ("peppertype2","Peppertype","writing","AI copy generation for marketing teams (by Pepper Content).","$35-199 mo","4.0",["writing","copywriting","marketing"],["Templates","Team workspace"],["Marketing teams"],["Variety"],["Merged into Pepper"]),
  ("longshot","Longshot AI","writing","Fact-based long-form AI writing with citations.","$19-49 mo","3.9",["writing","articles","facts"],["Fact-check","Citations","SEO"],["Bloggers"],["Cited sources"],["Occasional inaccuracy"]),
  ("writer","Writer","writing","AI writing platform for enterprise brand consistency.","Custom","4.1",["writing","enterprise","brand"],["Brand voice","Guardrails"],["Enterprise"],["Compliant"],["Setup heavy"]),
  ("novelai","NovelAI","writing","Story and lore generation with private AI models.","$10-25 mo","4.2",["writing","fiction","roleplay"],["Story Gen","Lorebook"],["Writers","RPG fans"],["Private","Creative"],["Controversial"]),
  ("ai-writer","AI-Writer","writing","Fact-based article generation with citations.","$29-59 mo","3.9",["writing","articles","research"],["Cited sources","Research"],["Bloggers"],["Cited"],["UI dated"]),
  ("textblaze","TextBlaze","writing","Smart text snippets and templates that work everywhere.","Freemium / $2.5 mo","4.5",["writing","productivity","snippets"],["Dynamic snippets","Forms"],["Support","Ops"],["Huge time-saver"],["Chrome-centric"]),
  ("jasper-ai","Jasper","writing","Enterprise AI marketing copilot with brand voice and campaigns.","$39-99 mo","4.2",["writing","marketing","enterprise"],["Brand voice","Campaigns","Art"],["Marketing teams"],["Polished suite"],["Pricey"]),

  # IMAGE & DESIGN
  ("canva","Canva","image","Drag-and-drop design with Magic Studio AI for solo creators.","Freemium / $15 mo","4.6",["image","design","templates"],["Templates","Magic Design","Brand kit"],["Everyone","Solopreneurs"],["Easy","Vast library"],["Generic output"]),
  ("leonardo-ai","Leonardo.Ai","image","Game-asset and concept art generation with fine control.","Freemium / $10 mo","4.3",["image","art","gaming"],["Image gen","Training","Canvas"],["Game devs","Artists"],["Asset control"],["Credit limits"]),
  ("adobe-firefly","Adobe Firefly","image","Adobe's commercial-safe generative image and video models.","Free / sub","4.4",["image","design","commercial"],["Generative fill","Text effects"],["Designers"],["Commercial-safe"],["Ecosystem lock-in"]),
  ("ideogram","Ideogram","image","AI image generation with accurate text rendering.","Freemium / $8 mo","4.3",["image","text","logos"],["Text in images","Styles"],["Designers","Marketers"],["Great text"],["Limited editing"]),
  ("recraft","Recraft","image","Vector and raster AI design with brand kits.","Freemium / $10 mo","4.3",["image","vector","branding"],["Vector gen","Brand kit"],["Designers"],["Vector output"],["Newer"]),
  ("krea","Krea","image","Real-time AI canvas with enhancement and upscale.","Freemium","4.2",["image","realtime","editing"],["Realtime canvas","Upscale"],["Artists"],["Realtime fun"],["Beta feel"]),
  ("playground","Playground AI","image","Image generation and simple editing for social content.","Freemium / $10 mo","4.0",["image","social","editing"],["Image gen","Edit","Layouts"],["Social creators"],["Easy"],["Less pro"]),
  ("photoroom","PhotoRoom","image","AI product photo and background removal for e-commerce.","Freemium / $13 mo","4.4",["image","ecommerce","removal"],["Bg removal","Batch","Retouch"],["Sellers","Shops"],["E-commerce focus"],["Watermark free tier"]),
  ("remove-bg","Remove.bg","image","One-click background removal API and app.","Freemium / $9 mo","4.5",["image","removal","api"],["Instant removal","API"],["Everyone"],["Instant","API"],["Limited edits"]),
  ("clipdrop","Clipdrop","image","Image cleanup, upscaling, and relight toolkit by Stability.","Freemium / $9 mo","4.1",["image","editing","upscale"],["Uncrop","Relight","Cleanup"],["Creators"],["Handy tools"],["Scattered"]),
  ("stability","Stable Diffusion","image","Open-weight image model you can self-host or use via API.","Free / API","4.3",["image","open","api"],["Open weights","API","ControlNet"],["Dev","Artists"],["Open","Flexible"],["Setup needed"]),
  ("fooocus","Fooocus","image","Minimalist Stable Diffusion UX for beginners.","Free (local)","4.2",["image","local","open"],["One-click","Local run"],["Hobbyists"],["Simple"],["Local only"]),
  ("designify","Designify","image","Auto background removal and design enhancement.","Freemium","4.0",["image","ecommerce","editing"],["Bg removal","Enhance"],["Sellers"],["Quick"],["Basic"]),
  ("vectorizer","Vectorizer.AI","image","AI raster-to-vector conversion with clean edges.","Freemium / $10 mo","4.3",["image","vector","conversion"],["Auto trace","Format export"],["Designers"],["Clean vectors"],["Niche"]),
  ("khroma","Khroma","image","AI color palette generator trained on your tastes.","Free","4.0",["image","color","branding"],["Palette ML","Search"],["Designers"],["Fun"],["Palette only"]),
  ("brandmark","Brandmark","image","AI logo and brand identity generator.","$25-145","3.9",["image","logo","branding"],["Logo gen","Brand kit"],["Startups"],["Fast branding"],["Generic"]),
  ("looka","Looka","image","Logo and brand kit generator with one-click assets.","$20-200","4.0",["image","logo","branding"],["Logo","Kit","Website"],["Startups","Solo"],["Quick brand"],["Template feel"]),
  ("designevo","DesignEvo","image","Easy logo maker with thousands of templates.","Freemium / $49","3.8",["image","logo","templates"],["Templates","Exports"],["Small biz"],["Simple"],["Templatey"]),
  ("artbreeder","Artbreeder","image","Collaborative image gene mixing and breeding.","Freemium","4.0",["image","art","blend"],["Gene mix","Collage"],["Artists"],["Creative blend"],["Niche"]),
  ("nightcafe","NightCafe","image","Community AI art generator with multiple models.","Freemium / $6 mo","4.1",["image","art","community"],["Multiple models","Community"],["Hobbyists"],["Variety"],["Credit limits"]),
  ("getimg","getimg.ai","image","Image models, inpainting, and custom model training.","Freemium / $12 mo","4.1",["image","editing","models"],["Inpaint","DreamBooth"],["Creators"],["Flexible"],["Credits"]),
  ("dreamstudio","DreamStudio","image","Official Stable Diffusion XL hosted UI.","Free / API","4.0",["image","open","api"],["SDXL","Params"],["Dev","Artists"],["SDXL quality"],["UI plain"]),
  ("magician","Magician","image","AI design plugins for Figma (copy + visuals).","$12 mo","4.0",["image","figma","ui"],["Figma plugins","Icons"],["Designers"],["Figma-native"],["Figma only"]),
  ("galileo-ai","Galileo AI","image","UI design generation from text prompts.","Waitlist / paid","3.9",["image","ui","figma"],["UI gen","Components"],["Product designers"],["Fast UI"],["Limited"]),
  ("uxpilot","UXPilot","image","AI UX ideation and wireframe generation.","Freemium","3.8",["image","ui","wireframe"],["Wireframes","Ideas"],["UX designers"],["Ideation"],["Early"]),
  ("lensa","Lensa","image","AI photo editor and avatar (magic avatars) app.","Freemium / $8 mo","3.9",["image","avatar","mobile"],["Magic avatars","Edits"],["Mobile users"],["Mobile fun"],["Controversy"]),

  # VIDEO & AUDIO
  ("descript","Descript","video","Transcript-based audio/video editing with overdub.","Freemium / $12 mo","4.5",["video","audio","editing"],["Transcript edit","Overdub","Filler"],["Podcasters","YT"],["Edit by text"],["Corpus training"]),
  ("elevenlabs","ElevenLabs","video","Best-in-class AI voice cloning and text-to-speech.","Freemium / $5 mo","4.6",["video","audio","voice"],["Voice clone","Dubbing","API"],["Creators","Devs"],["Realistic voice"],["Deepfake risk"]),
  ("runway","Runway","video","Generative video, editing, and magic tools (Gen-2/3).","Freemium / $12 mo","4.4",["video","generation","editing"],["Text-to-video","Gen tools","Motion"],["Filmmakers","Creators"],["Cutting-edge"],["Credits"]),
  ("pika","Pika","video","Text/image-to-video generation with Pikaffects.","Freemium / $8 mo","4.3",["video","generation","fun"],["Text-to-video","Effects"],["Creators"],["Playful"],["Short clips"]),
  ("heygen","HeyGen","video","AI avatar spokes video from a script in minutes.","Freemium / $24 mo","4.3",["video","avatar","presenter"],["Avatar video","Translate lip-sync"],["Marketers","Trainers"],["No camera needed"],["Avatar uncanny"]),
  ("captions","Captions","video","AI captions, eye-contact, and talking-head edits.","Freemium / $10 mo","4.2",["video","captions","mobile"],["Auto captions","Eye contact"],["Shorts creators"],["Mobile-first"],["Mobile only"]),
  ("opus-clip","Opus Clip","video","Turn long videos into viral short clips with AI.","Freemium / $19 mo","4.3",["video","shorts","clipping"],["Auto clip","Virality score"],["YT","Podcasters"],["Shorts engine"],["Hit-or-miss"]),
  ("pictory","Pictory","video","Script/article-to-video with stock and captions.","$19-39 mo","4.1",["video","articles","stock"],["Script-to-video","Summaries"],["Marketers"],["From text"],["Stock generic"]),
  ("synthesia","Synthesia","video","120+ language AI avatar video platform.","$22-67 mo","4.4",["video","avatar","enterprise"],["140 avatars","Languages","Templates"],["L&D","Enterprise"],["Scales video"],["Subscription"]),
  ("veed","Veed.io","video","Browser video editor with auto-subtitle and cleanup.","Freemium / $12 mo","4.2",["video","editing","subtitles"],["Subtitles","Trim","Enhance"],["Creators"],["Browser-based"],["Watermark free"]),
  ("kaiber","Kaiber","video","AI music-video and motion generation from images.","$5-25 mo","4.0",["video","music","motion"],["Motion","Audio reactive"],["Artists"],["Artistic"],["Niche"]),
  ("murf","Murf","video","Studio-quality AI voiceovers for videos and ads.","Freemium / $19 mo","4.3",["video","voice","voiceover"],["Voice library","Sync"],["Marketers"],["Natural VO"],["Less cloning"]),
  ("kling","Kling AI","video","High-fidelity text-to-video with long durations.","Freemium / $10 mo","4.2",["video","generation","realistic"],["Long clips","Realism"],["Creators"],["Longer clips"],["Queue waits"]),
  ("luma-dream","Luma Dream Machine","video","High-quality text/image-to-video by Luma.","Freemium / $10 mo","4.3",["video","generation","realistic"],["Smooth motion","Camera"],["Creators"],["Quality"],["Credits"]),
  ("hailuo","Hailuo AI","video","MiniMax's text-to-video with strong motion.","Freemium","4.1",["video","generation"],["Text-to-video","Motion"],["Creators"],["Strong motion"],["Newer"]),
  ("wisecut","Wisecut","video","Auto jump-cuts and subtitle for talking videos.","Freemium / $10 mo","4.0",["video","editing","shorts"],["Jump cuts","Subtitles"],["YT"],["Auto edit"],["Generic"]),
  ("fliki","Fliki","video","Text-to-video with lifelike AI voices and stock.","Freemium / $21 mo","4.2",["video","voice","articles"],["Voice + video","Stock"],["Marketers"],["Voice strong"],["Stock reuse"]),
  ("riverside","Riverside","video","Studio-quality remote recording (audio + 4K video).","Freemium / $15 mo","4.4",["video","podcast","recording"],["Local record","Magic Clips"],["Podcasters"],["Clean record"],["Edit add-on"]),
  ("capcut","CapCut","video","TikTok's free editor with AI features (auto-cut, captions).","Freemium / $8 mo","4.5",["video","editing","shorts"],["Auto captions","Templates"],["Shorts creators"],["Free","Powerful"],["Watermark (free)"]),
  ("wondershare-filmora","Filmora","video","Consumer video editor with AI assist.","$49-80 yr","4.2",["video","editing","templates"],["Templates","AI tools"],["Beginners"],["Easy"],["Mid tier"]),
  ("vizard","Vizard.ai","video","Long video to clips, with transcript and edits.","Freemium / $16 mo","4.0",["video","clipping","shorts"],["Auto clip","Subtitles"],["Creators"],["Clipping"],["Similar tools"]),
  ("submagic","Submagic","video","AI captions and B-rolls for short-form video.","$10-30 mo","4.1",["video","captions","shorts"],["Captions","Emojis","B-roll"],["Shorts creators"],["Punchy captions"],["Shorts only"]),
  ("topaz-video","Topaz Video AI","video","AI upscaling and denoise for video footage.","$299","4.3",["video","upscale","enhance"],["Upscale","Deinterlace"],["Filmmakers"],["Quality lift"],["Pricey"]),
  ("adrift","Adobe Podcast","video","AI audio cleaning and remote podcast recording.","Freemium","4.3",["video","audio","podcast"],["Enhance Speech","Studio"],["Podcasters"],["Speech clean"],["Adobe acct"]),
  ("krisp","Krisp","video","AI noise cancellation for calls and recordings.","Freemium / $8 mo","4.4",["video","audio","calls"],["Noise cancel","Transcribe"],["Remote workers"],["Crisp audio"],["Call-only"]),
  ("speechify","Speechify","video","Text-to-speech reader for docs and web.","Freemium / $11 mo","4.0",["video","audio","tts"],["Listen docs","Voices"],["Readers"],["Convenient"],["Voices limited"]),
  ("listnr","Listnr","video","AI voice generation and podcast hosting.","Freemium / $19 mo","3.9",["video","audio","tts"],["Voices","Hosting"],["Creators"],["Variety"],["Quality varies"]),
  ("respeecher","Respeecher","video","Voice cloning for film, games, and localization.","Custom","4.1",["video","voice","clone"],["Voice clone","Localization"],["Studios"],["Pro voice"],["Enterprise only"]),

  # AUTOMATION & WORKFLOW
  ("zapier","Zapier","automation","Connect 6,000+ apps with no-code automated workflows.","Freemium / $20 mo","4.5",["automation","workflow","nocode"],["6k+ apps","Multi-step","AI"],["Solopreneurs","Teams"],["Huge app library"],["Cost at scale"]),
  ("make","Make","automation","Visual no-code automation with branching scenarios.","Freemium / $9 mo","4.4",["automation","workflow","visual"],["Visual builder","Scenarios"],["Ops","Agencies"],["Powerful visual"],["Steeper learning"]),
  ("n8n","n8n","automation","Open-source workflow automation you can self-host.","Freemium / $20 mo","4.5",["automation","workflow","open"],["Self-host","Fair-code","Code nodes"],["Devs","Ops"],["Open","Flexible"],["Self-host setup"]),
  ("ifttt","IFTTT","automation","Simple applets connecting consumer apps and devices.","Freemium / $3 mo","4.1",["automation","workflow","simple"],["Applets","Smart home"],["Consumers"],["Dead simple"],["Limited logic"]),
  ("pipedream","Pipedream","automation","Code-first automation with 2,000+ APIs.","Freemium / $20 mo","4.3",["automation","api","workflow"],["Code steps","API integrations"],["Devs"],["Code + no-code"],["Dev leaning"]),
  ("tray","Tray.io","automation","General-purpose automation for business teams.","Custom","4.1",["automation","enterprise","workflow"],["Citizen automators","API"],["Enterprise"],["Scalable"],["Costly"]),
  ("workato","Workato","automation","Enterprise iPaaS with recipe automation.","Custom","4.2",["automation","enterprise","integration"],["Recipes","Integrations"],["Enterprise"],["Deep integrations"],["Expensive"]),
  ("relay","Relay.app","automation","Human-in-the-loop automation with AI steps.","Freemium / $10 mo","4.2",["automation","workflow","ai"],["Human steps","AI assist"],["Teams"],["Human-in-loop"],["Newer"]),
  ("beautiful-ai","Beautiful.ai","automation","AI slide design that builds decks automatically.","$12-40 mo","4.1",["automation","presentations","design"],["Smart templates","Brand"],["Presenters"],["Auto decks"],["Less control"]),
  ("tome","Tome","automation","AI-generated narratives and decks from a prompt.","Freemium / $8 mo","4.0",["automation","presentations","ai"],["Prompt decks","Embed"],["Founders"],["Fast decks"],["Generic"]),
  ("gamma","Gamma","automation","AI presentations, docs, and webpages from prompts.","Freemium / $10 mo","4.2",["automation","presentations","docs"],["Decks","Docs","Web"],["Teams"],["Versatile"],["Format limits"]),
  ("bardeen","Bardeen","automation","Browser automation playbooks with AI.","Freemium","4.0",["automation","browser","nocode"],["Playbooks","Scraper"],["Founders"],["Browser magic"],["Chrome only"]),
  ("browserbear","BrowserBear","automation","No-code browser automation API (screenshots, scrape).","$29 mo","3.9",["automation","browser","api"],["API","Tasks"],["Devs"],["API simple"],["Niche"]),
  ("axiom","Axiom.ai","automation","Browser and desktop automation without code.","$15 mo","3.9",["automation","browser","rpa"],["Bot builder","Scheduler"],["Ops"],["Visual RPA"],["Flaky"]),
  ("airtable","Airtable","automation","Spreadsheet-database hybrid with automations.","Freemium / $20 mo","4.4",["automation","database","nocode"],["Bases","Automations","Interfaces"],["Teams","Ops"],["Flexible data"],["Pricey scale"]),
  ("notion","Notion","automation","All-in-one docs, wikis, and databases with AI.","Freemium / $8 mo","4.5",["automation","notes","workspace"],["Docs","DB","AI"],["Everyone"],["Versatile"],["Sync slow"]),
  ("clickup","ClickUp","automation","Project management with built-in AI and automations.","Freemium / $7 mo","4.2",["automation","pm","workspace"],["Tasks","Docs","AI"],["Teams"],["All-in-one"],["Overwhelming"]),
  ("monday","monday.com","automation","Work OS with visual automations and boards.","$9-19 mo","4.2",["automation","pm","workflow"],["Boards","Automations"],["Teams"],["Visual"],["Add-ons"]),
  ("coda","Coda","automation","Doc + table hybrid with AI and automations.","Freemium / $10 mo","4.1",["automation","docs","workspace"],["Docs+Tables","Packs"],["Teams"],["Flexible"],["Learning curve"]),
  ("retool","Retool","automation","Build internal tools fast with components + code.","Freemium / $10 mo","4.3",["automation","internal-tools","lowcode"],["Components","DB connect"],["Devs","Ops"],["Fast internal tools"],["Dev leaning"]),
  ("cal-com","Cal.com","automation","Open-source scheduling with routing automation.","Freemium / $12 mo","4.3",["automation","scheduling","open"],["Routing","Integrations"],["Teams"],["Open","Flexible"],["Setup"]),
  ("calendly","Calendly","automation","Popular scheduling links with workflow automation.","Freemium / $8 mo","4.4",["automation","scheduling"],["Round-robin","Workflows"],["Everyone"],["Ubiquitous"],["Free tier thin"]),
  ("typeform","Typeform","automation","Conversational forms with logic and integrations.","Freemium / $25 mo","4.3",["automation","forms","surveys"],["Logic jumps","Integrations"],["Marketers"],["Engaging"],["Pricey"]),

  # PRODUCTIVITY & RESEARCH
  ("chatgpt","ChatGPT","productivity","OpenAI's conversational AI for writing, coding, and research.","Freemium / $20 mo","4.7",["productivity","chat","research"],["GPT-4o","Vision","Voice"],["Everyone"],["Versatile","Fast"],["Hallucinations"]),
  ("claude","Claude","productivity","Anthropic's helpful, harmless AI for long-form reasoning.","Freemium / $20 mo","4.7",["productivity","chat","reasoning"],["200K context","Artifacts","Vision"],["Writers","Devs"],["Long context","Thoughtful"],["Not real-time"]),
  ("perplexity","Perplexity","productivity","AI answer engine with cited sources and search.","Freemium / $20 mo","4.5",["productivity","research","search"],["Citations","Spaces","Voice"],["Researchers"],["Cited answers"],["Limited depth"]),
  ("gemini","Google Gemini","productivity","Google's multimodal AI across Workspace apps.","Freemium / $20 mo","4.4",["productivity","chat","research"],["Multimodal","Workspace"],["Google users"],["Workspace-native"],["Bias concerns"]),
  ("you-com","You.com","productivity","AI search assistant with custom agents.","Freemium","4.1",["productivity","search","chat"],["Agents","Search"],["Researchers"],["Agentic"],["Smaller"]),
  ("phind","Phind","productivity","AI search tuned for developers and code.","Freemium","4.2",["productivity","code","search"],["Code answers","Citations"],["Devs"],["Dev-focused"],["Niche"]),
  ("consensus","Consensus","productivity","AI search across 200M+ research papers.","Freemium / $12 mo","4.1",["productivity","research","papers"],["Paper search","Citations"],["Researchers","Students"],["Evidence-based"],["Academic only"]),
  ("scite","scite","productivity","Smart citations that show context (supporting/contrasting).","Freemium / $10 mo","4.0",["productivity","research","citations"],["Citation context","Assistant"],["Academics"],["Smart cites"],["Niche"]),
  ("elicit","Elicit","productivity","AI literature review and extraction from papers.","Freemium / $12 mo","4.1",["productivity","research","papers"],["Extraction","Summarize"],["Researchers"],["Review fast"],["Limited"]),
  ("jenni","Jenni","productivity","AI writing assistant for academic and research papers.","Freemium / $20 mo","3.9",["productivity","writing","research"],["Autocomplete","Citations"],["Students"],["Paper help"],["Academic integrity"]),
  ("mem","Mem","productivity","AI-native note app that surfaces related notes.","Freemium / $8 mo","3.8",["productivity","notes","ai"],["Auto-org","Search"],["Knowledge workers"],["Smart recall"],["Early"]),
  ("rewind","Rewind","productivity","Record and search everything you've seen on screen.","$20 mo","3.9",["productivity","search","memory"],["Screen recall","OCR"],["Power users"],["Total recall"],["Privacy"]),
  ("raycast","Raycast","productivity","Blazing-fast launcher with AI commands and extensions.","Freemium / $8 mo","4.6",["productivity","mac","launcher"],["Launcher","AI","Extensions"],["Mac users"],["Huge time-saver"],["Mac only"]),
  ("taskade","Taskade","productivity","AI workspace for tasks, docs, and team agents.","Freemium / $10 mo","4.1",["productivity","tasks","ai"],["Tasks","Agents","Mind maps"],["Teams"],["AI agents"],["Busy UI"]),
  ("todoist-ai","Todoist","productivity","Popular task manager with AI task breakdown.","Freemium / $4 mo","4.4",["productivity","tasks"],["Quick add","AI sort"],["Everyone"],["Reliable"],["AI add-on"]),
  ("motion","Motion","productivity","AI calendar that auto-schedules your tasks.","$19-34 mo","4.2",["productivity","calendar","ai"],["Auto-schedule","Calendar"],["Professionals"],["Time-saving"],["Pricey"]),
  ("reclaim","Reclaim AI","productivity","Auto-plan calendar around tasks and habits.","Freemium / $8 mo","4.1",["productivity","calendar","ai"],["Habit sync","Calendar"],["Teams"],["Google-native"],["Google only"]),
  ("fireflies","Fireflies.ai","productivity","AI meeting notetaker and CRM sync.","Freemium / $10 mo","4.3",["productivity","meetings","notes"],["Transcribe","Search","CRM"],["Teams"],["Meeting notes"],["Bot joins"]),
  ("fathom","Fathom","productivity","Free AI call recorder with highlights.","Freemium","4.3",["productivity","meetings","notes"],["Highlights","Summary"],["Sellers"],["Free","Clean"],["Zoom-centric"]),
  ("otter","Otter.ai","productivity","Live transcription and meeting notes.","Freemium / $10 mo","4.1",["productivity","meetings","transcription"],["Live notes","Search"],["Teams"],["Live transcribe"],["Accuracy varies"]),
  ("reflect","Reflect","productivity","AI note app with backlinked graph and syncing.","$8 mo","4.0",["productivity","notes","graph"],["Backlinks","Sync"],["Thinkers"],["Clean notes"],["Niche"]),
  ("obsidian-copilot","Obsidian Copilot","productivity","AI assistant inside Obsidian vaults.","Freemium","3.9",["productivity","notes","ai"],["Local LLM","Chat vault"],["Obsidian users"],["Vault-native"],["Plugin setup"]),

  # CODING & BUILD
  ("github-copilot","GitHub Copilot","coding","AI pair programmer inside your editor.","$10-19 mo","4.4",["coding","pair-programmer","ide"],["Inline completions","Chat"],["Devs"],["Saves typing"],["Costly"]),
  ("cursor","Cursor","coding","AI-first code editor built on VS Code.","Freemium / $20 mo","4.6",["coding","editor","ai"],["Chat","Edit","Composer"],["Devs"],["Best AI editor"],["VS Code fork"]),
  ("claudecode","Claude Code","coding","Agentic CLI that writes, tests, and commits code.","$20 mo","4.4",["coding","agent","cli"],["File ops","Tests","Git"],["Devs"],["Autonomous"],["API cost"]),
  ("tabnine","Tabnine","coding","Privacy-focused AI code completion.","Freemium / $12 mo","4.1",["coding","completion","privacy"],["Local models","Team"],["Devs"],["Private"],["Less capable"]),
  ("codeium","Codeium","coding","Free AI coding assistant with chat and search.","Freemium / $15 mo","4.3",["coding","completion","free"],["Autocomplete","Chat"],["Devs"],["Free","Fast"],["Occasional misses"]),
  ("replit","Replit","coding","Browser IDE with AI agent that ships apps.","Freemium / $20 mo","4.3",["coding","ide","agent"],["Agent","Hosting","DB"],["Builders"],["Ship in browser"],["Limited scale"]),
  ("bolt","Bolt.new","coding","Prompt-to-fullstack-app in the browser.","Freemium / $15 mo","4.2",["coding","fullstack","prompt"],["Fullstack gen","Deploy"],["Founders"],["No setup"],["Buggy gen"]),
  ("v0","v0.dev","coding","Generate React UI from text and images.","Freemium / $20 mo","4.2",["coding","ui","react"],["React gen","Tailwind"],["Frontend"],["Clean UI"],["React only"]),
  ("lovable","Lovable","coding","Describe an app, get a deployed fullstack build.","Freemium / $20 mo","4.3",["coding","fullstack","nocode"],["Fullstack","Deploy","Supabase"],["Founders"],["Ships apps"],["Vendor lock"]),
  ("windsurf","Windsurf","coding","AI editor with Cascade agentic flow.","Freemium / $15 mo","4.3",["coding","editor","agent"],["Cascade","Chat"],["Devs"],["Agentic"],["Newer"]),
  ("aider","Aider","coding","Terminal pair programmer that edits your repo.","Free / $","4.4",["coding","cli","open"],["Repo edits","Git"],["Devs"],["Repo-aware"],["Terminal UX"]),
  ("cline","Cline","coding","Open-source autonomous coding agent in VS Code.","Free / API","4.3",["coding","agent","open"],["Plan/act","Tools"],["Devs"],["Open","Autonomous"],["API cost"]),
  ("devin","Devin","coding","Autonomous AI software engineer (Cognition).","$500 mo","3.9",["coding","agent","autonomous"],["PRs","Shell","Browser"],["Eng teams"],["Autonomous"],["Very pricey"]),
  ("sweep","Sweep","coding","AI junior dev that turns issues into PRs.","Freemium / $","3.8",["coding","pr","agent"],["Issue to PR"],["Teams"],["Auto PRs"],["Hit-or-miss"]),
  ("sourcegraph","Sourcegraph Cody","coding","AI coding with codebase-wide context.","Freemium / $9 mo","4.0",["coding","context","search"],["Repo context","Chat"],["Devs"],["Knows repo"],["Setup"]),
  ("codeparrot","CodeParrot","coding","AI UI components from descriptions.","Freemium","3.8",["coding","ui","components"],["Component gen"],["Frontend"],["Components"],["Narrow"]),
  ("pythagora","Pythagora","coding","AI builds full apps from a single prompt.","Freemium","3.8",["coding","fullstack","agent"],["Full app gen"],["Builders"],["Ambitious"],["Early"]),
  ("vanna","Vanna","coding","AI SQL generation from natural language.","Freemium / API","3.9",["coding","sql","data"],["NL to SQL","Connectors"],["Analysts"],["SQL help"],["DB setup"]),
  ("supabase-ai","Supabase AI","coding","AI SQL and schema help inside Supabase.","Free / plan","3.9",["coding","sql","database"],["SQL gen","Schema"],["Devs"],["DB-native"],["Supabase only"]),
  ("locofy","Locofy","coding","Design-to-code for React and React Native.","Freemium","3.7",["coding","design","react"],["Figma to code"],["Designers"],["D2C"],["Limited"]),
  ("anima","Anima","coding","Figma to code (React, Vue, HTML).","Freemium / $","3.7",["coding","design","figma"],["Figma to code"],["Designers"],["D2C"],["Flaky"]),
  ("blackbox","Blackbox AI","coding","AI coding copilot with code search.","Freemium / $","3.8",["coding","search","completion"],["Code search","Complete"],["Devs"],["Search"],["Variable"]),
  ("mutable","Mutable.ai","coding","AI autobuild for Python notebooks and code.","Freemium","3.7",["coding","python","agent"],["Auto build","Notebooks"],["Data sci"],["Notebook AI"],["Early"]),

  # MARKETING & SEO
  ("jasper2","Jasper","marketing","AI brand marketing platform (campaigns, art, chat).","$39-99 mo","4.2",["marketing","copy","brand"],["Brand voice","Campaigns"],["Marketing teams"],["Enterprise-ready"],["Pricey"]),
  ("surfer","Surfer","marketing","On-page SEO content optimization and audits.","$59-139 mo","4.4",["marketing","seo","content"],["Content score","Audit"],["SEO"],["Rank-focused"],["Pricey"]),
  ("semrush","Semrush","marketing","All-in-one SEO, PPC, and competitor research suite.","$120-450 mo","4.5",["marketing","seo","research"],["Keyword","Backlinks","Audit"],["Agencies"],["Comprehensive"],["Expensive"]),
  ("ahrefs","Ahrefs","marketing","Backlink and SEO analysis with content explorer.","$99-999 mo","4.6",["marketing","seo","backlinks"],["Site audit","Keywords"],["SEO pros"],["Best backlinks"],["Pricey"]),
  ("neuronwriter","NeuronWriter","marketing","SEO content editor with NLP recommendations.","$19-59 mo","4.2",["marketing","seo","content"],["NLP terms","Editor"],["Bloggers"],["Affordable SEO"],["UI plain"]),
  ("outranking","Outranking","marketing","SEO content briefs and AI writing.","$29-189 mo","3.9",["marketing","seo","briefs"],["Briefs","Writing"],["SEO"],["Briefs"],["Costly"]),
  ("postwise","Postwise","marketing","AI Twitter/X growth tool for threads and scheduling.","$29-59 mo","3.9",["marketing","social","twitter"],["Threads","Schedule"],["Solopreneurs"],["Twitter growth"],["X-only"]),
  ("hypefury","Hypefury","marketing","Schedule and grow on X/Twitter with smart retries.","$15-40 mo","4.0",["marketing","social","twitter"],["Smart scheduling","Hooks"],["Creators"],["Growth"],["X-centric"]),
  ("predis","Predis.ai","marketing","AI social posts and competitor analysis.","Freemium / $27 mo","4.0",["marketing","social","design"],["Post gen","Carousels"],["Solopreneurs"],["Visual posts"],["Social only"]),
  ("lately","Lately","marketing","AI turns long content into social posts.","Custom","3.8",["marketing","social","repurpose"],["Repurpose","Schedule"],["Teams"],["Repurpose"],["Costly"]),
  ("ocoya","Ocoya","marketing","AI social content with scheduling and designs.","$15-59 mo","3.9",["marketing","social","design"],["Post gen","Calendar"],["Solopreneurs"],["Combined"],["Generic"]),
  ("brandwell","BrandWell","marketing","Long-form AI content with SEO and brand tone.","$99-400 mo","3.9",["marketing","content","seo"],["Long-form","Brand"],["Agencies"],["Branded"],["Pricey"]),
  ("mailmodo","Mailmodo","marketing","Interactive AMP email marketing.","$39-599 mo","3.9",["marketing","email","automation"],["AMP email","Automation"],["Marketers"],["Interactive"],["Deliverability"]),
  ("instantly","Instantly.ai","marketing","Cold email outreach at scale with AI.","$30-145 mo","4.0",["marketing","email","outreach"],["Warmup","Campaigns"],["Agencies"],["Scale outreach"],["Spam risk"]),
  ("smartlead","Smartlead","marketing","Cold email with unlimited warmup and AI.","$34-99 mo","4.0",["marketing","email","outreach"],["Warmup","AI rotate"],["Outreach"],["Deliverability"],["learning"]),
  ("klaviyo","Klaviyo","marketing","E-commerce email/SMS automation with AI.","Freemium / $","4.3",["marketing","email","ecommerce"],["Flows","Segmentation"],["E-com"],["E-com native"],["E-com only"]),
  ("adcreative","AdCreative.ai","marketing","AI ad creatives and banners that convert.","$21-99 mo","4.0",["marketing","ads","design"],["Ad gen","Scores"],["Advertisers"],["Fast ads"],["Generic"]),
  ("mutiny","Mutiny","marketing","AI website personalization for B2B.","Custom","3.9",["marketing","personalization","b2b"],["Personalize","No-code"],["B2B"],["CRO"],["Enterprise"]),
  ("optimizely","Optimizely","marketing","Experimentation and AI personalization.","Custom","4.0",["marketing","experiment","enterprise"],["A/B","Personalize"],["Enterprise"],["Robust"],["Costly"]),
  ("rankmath","Rank Math","marketing","AI SEO plugin for WordPress.","Freemium / $","4.3",["marketing","seo","wordpress"],["Schema","Content AI"],["Bloggers"],["WP-native"],["WP only"]),
  ("yoast","Yoast SEO","marketing","Popular WordPress SEO plugin with AI.","Freemium / $","4.1",["marketing","seo","wordpress"],["Readability","Schema"],["Bloggers"],["Trusted"],["Upsells"]),
  ("growthbar","GrowthBar","marketing","AI SEO writing and keyword research.","$29-129 mo","3.9",["marketing","seo","writing"],["Keywords","AI write"],["Bloggers"],["Simple SEO"],["Limited"]),

  # BUSINESS & FINANCE
  ("doola","Doola","business","Formation, banking, and bookkeeping for US startups.","From $","4.1",["business","formation","finance"],["LLC/Corp","Bookkeeping"],["Founders"],["US launch"],["US only"]),
  ("stripe","Stripe","business","Payments and billing infrastructure for the internet.","Per txn","4.6",["business","payments","api"],["Payments","Billing","Radar"],["Devs"],["Industry std"],["Dev needed"]),
  ("square","Square","business","Point-of-sale and payments for small business.","Per txn","4.3",["business","payments","pos"],["POS","Invoices"],["Retail"],["Easy POS"],["Fees"]),
  ("quickbooks","QuickBooks","business","Small-business accounting and taxes.","$15-100 mo","4.0",["business","accounting","finance"],["Invoicing","Tax"],["SMB"],["Established"],["Pricey"]),
  ("wave","Wave","business","Free accounting and invoicing for small biz.","Free / pay","4.1",["business","accounting","invoicing"],["Invoicing","Accounting"],["Solopreneurs"],["Free"],["Add-ons"]),
  ("freshbooks","FreshBooks","business","Invoicing and expense tracking for freelancers.","$17-55 mo","4.0",["business","invoicing","freelance"],["Invoices","Time"],["Freelancers"],["Freelance-fit"],["Limited"]),
  ("xero","Xero","business","Cloud accounting for small business.","$13-70 mo","4.1",["business","accounting","finance"],["Bank rec","Invoicing"],["SMB"],["Solid"],["Learning curve"]),
  ("ramp","Ramp","business","Corporate cards with AI spend automation.","Free / %","4.3",["business","finance","spend"],["Cards","Savings"],["Startups"],["Saves money"],["US"]),
  ("brex","Brex","business","Corporate cards and expense management.","Free / %","4.1",["business","finance","expense"],["Cards","Expenses"],["Startups"],["Startup-fit"],["US"]),
  ("mercury","Mercury","business","Banking built for startups (virtual cards, API).","Free / %","4.4",["business","banking","startups"],["Virtual cards","API"],["Startups"],["Modern banking"],["US only"]),
  ("bill","BILL","business","AP/AR automation and payments for SMB.","$0-45 mo","3.9",["business","finance","ap"],["Payables","Receivables"],["SMB"],["AP/AR"],["Fees"]),
  ("expensify","Expensify","business","Expense reporting and receipt scanning.","Freemium / $","4.0",["business","expense","finance"],["Scan","Approval"],["Teams"],["Receipts"],["UI old"]),
  ("puzzle","Puzzle","business","AI bookkeeping that categorizes transactions.","$19-99 mo","3.9",["business","accounting","ai"],["Auto-categorize","Insights"],["Startups"],["AI books"],["Newer"]),
  ("indy","Indy","business","All-in-one freelancer suite (CRM, proposals, invoicing).","$9-30 mo","3.8",["business","freelance","crm"],["Proposals","Invoices"],["Freelancers"],["Freelance suite"],["Early"]),
  ("bonsai","Bonsai","business","Freelance OS: proposals, contracts, and taxes.","$19-32 mo","4.0",["business","freelance","contracts"],["Proposals","Contracts","Tax"],["Freelancers"],["Polished suite"],["Pricey"]),
  ("hiveage","Hiveage","business","Online invoicing and billing for small biz.","$7-39 mo","3.8",["business","invoicing","billing"],["Invoices","Billing"],["SMB"],["Simple"],["Dated"]),
  ("and-co","AND.CO","business","Free invoicing and contracts for freelancers.","Free / $","3.7",["business","freelance","invoicing"],["Invoices","Contracts"],["Freelancers"],["Free"],["Basic"]),
  ("harvest","Harvest","business","Time tracking and invoicing for teams.","Freemium / $12 mo","4.3",["business","time","invoicing"],["Time","Invoices"],["Agencies"],["Reliable"],["Limited"]),
  ("toggl","Toggl","business","Simple time tracking with AI insights.","Freemium / $10 mo","4.3",["business","time","tracking"],["One-click","Reports"],["Teams"],["Easy track"],["No billing"]),
  ("zoho-books","Zoho Books","business","Accounting inside the Zoho suite.","$0-60 mo","4.1",["business","accounting","suite"],["Books","Suite"],["SMB"],["Suite"],["Zoho lock-in"]),
  ("legalzoom","LegalZoom","business","Online legal formation and documents.","$0-349 + fees","3.9",["business","legal","formation"],["Formation","Docs"],["Founders"],["Easy legal"],["Upsells"]),
  ("docracy","Docracy","business","Free legal document templates.","Free","3.6",["business","legal","docs"],["Templates"],["Founders"],["Free docs"],["Limited"]),
  ("upmetrics","Upmetrics","business","AI business plan and financial forecasting.","$7-39 mo","3.8",["business","planning","finance"],["Plan gen","Forecast"],["Founders"],["Plans"],["Templatey"]),
  ("liveplan","LivePlan","business","Business planning and financial projections.","$12-20 mo","3.9",["business","planning","finance"],["Plans","Forecast"],["Founders"],["Established"],["Dated"]),
  ("causal","Causal","business","Spreadsheet alternative for models and finance.","$","3.9",["business","finance","modeling"],["Models","Dashboards"],["Finance"],["Clean models"],["Learning"]),
  ("jira","Jira","business","Agile project and issue tracking for dev teams.","Freemium / $","4.1",["business","pm","dev"],["Agile","Boards"],["Teams"],["Dev-standard"],["Heavy"]),
  ("asana","Asana","business","Work management with timelines and automations.","Freemium / $11 mo","4.1",["business","pm","workflow"],["Tasks","Timeline"],["Teams"],["Flexible"],["Overkill small"]),
  ("basecamp","Basecamp","business","Simple all-in-one project and team suite.","$15/user mo","4.0",["business","pm","team"],["Message","Tasks","Docs"],["SMB"],["Opinionated"],["Small feel"]),
  ("trello","Trello","business","Kanban boards with Butler automation.","Freemium / $5 mo","4.2",["business","pm","kanban"],["Boards","Butler"],["Teams"],["Easy"],["Simple only"]),
]
