#!/usr/bin/env python3
"""Seed 90+ additional real AI tools into data/tools/*.yaml.

Curated, factual entries across the 8 established categories. Idempotent:
re-running overwrites the same files. Affiliate left blank (wire later).

Run:  python scripts/seed_tools.py
Then: python scripts/build_directory.py && hugo --minify
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "data", "tools")

# slug, name, category, summary, pricing, rating, tags, features, best_for, pros, cons
T = [
 # ---- WRITING & CONTENT ----
 ("grammarly","Grammarly","writing","AI grammar, clarity, and tone checker that polishes everything you write.","Freemium — free tier; Premium $12/mo","4.7",["writing","editing","grammar"],
  ["Real-time grammar and clarity fixes","Tone and tone-rewrite suggestions","Plagiarism and citation checks"],
  ["Anyone publishing written work","Non-native English writers"],["Ubiquitous across apps","Fast, low-friction"],["Premium paywalled features","Can over-correct voice"]),
 ("copyai","Copy.ai","writing","Generative copy for ads, emails, and blogs with marketing templates.","Freemium — free tier; Pro $36/mo","4.4",["writing","marketing","copy"],
  ["Brand voice + workflows","30+ languages","Sales and marketing workflows"],
  ["Marketers needing volume","Agencies"],["Fast first drafts","Good template library"],["Quality varies by prompt","Pricey at scale"]),
 ("writesonic","Writesonic","writing","SEO-optimized article writer with a built-in chatbot and fact checker.","Freemium — free tier; Pro from $16/mo","4.3",["writing","seo","blog"],
  ["Article Writer 6.0 with citations","ChatSonic conversational search","Bulk article generation"],
  ["Bloggers at scale","SEO teams"],["Long-form capable","Fact-checking helps"],["Credits burn fast","Tone inconsistent"]),
 ("sudowrite","Sudowrite","writing","Fiction-first AI for novelists — brainstorm, describe, and rewrite prose.","Paid — from $10/mo","4.6",["writing","fiction","creative"],
  ["Show-don't-tell rewrites","Character and plot brainstorming","Voice-matched edits"],
  ["Novelists and storytellers","Creative writers"],["Excellent for prose","Understands craft"],["Niche use case","No business templates"]),
 ("rytr","Rytr","writing","Low-cost AI writer for short-form content and quick drafts.","Freemium — free tier; Unlimited $9/mo","4.2",["writing","copy","affordable"],
  ["40+ use cases","Tone and language control","Team billing"],
  ["Bootstrapped founders","Students"],["Very affordable","Simple UI"],["Weak long-form","Generic output"]),
 ("quillbot","QuillBot","writing","Paraphraser and summarizer with a grammar and citation toolkit.","Freemium — free tier; Premium $9.95/mo","4.4",["writing","paraphrase","study"],
  ["Paraphraser with modes","Summarizer and citation generator","Grammar checker"],
  ["Students and researchers","Editors"],["Great paraphrasing","Useful free tier"],["Not for drafting","Repetition risk"]),
 ("wordtune","Wordtune","writing","Rewrite and tone-shift suggestions that sound like you.","Freemium — free tier; Pro $9.99/mo","4.3",["writing","rewrite","tone"],
  ["Rewrite and shorten/expand","Tone matching","Spoken-grammar fixes"],
  ["Professionals polishing email","Non-native writers"],["Natural rewrites","Good Chrome add-on"],["Limited free","No long docs"]),
 ("anyword","Anyword","writing","Performance-written copy with predictive engagement scores.","Paid — from $39/mo","4.2",["writing","marketing","copy"],
  ["Predictive performance scores","Brand voice library","A/B message variants"],
  ["Performance marketers","Ecommerce"],["Data-backed copy","Good for ads"],["Pricey","Scores are estimates"]),
 ("frase","Frase","writing","SEO content briefs and AI drafts built from SERP research.","Paid — from $15/mo","4.4",["writing","seo","research"],
  ["SERP-based content briefs","AI answer engine","Outline builder"],
  ["SEO content teams","Agencies"],["Fast briefs","Tight SERP integration"],["No full site audit","Learning curve"]),
 ("surferseo","Surfer SEO","marketing","On-page SEO optimizer that scores content against top-ranking pages.","Paid — from $59/mo","4.5",["seo","writing","marketing"],
  ["Content Editor with NLP terms","SERP analyzer","Auto-optimize"],
  ["SEO writers","Agencies"],["Clear optimization target","Good audits"],["Pricey","Can keyword-stuff"]),
 ("jenni","Jenni","writing","Autocomplete writing assistant for academic and long-form drafts.","Freemium — free tier; Pro $20/mo","4.3",["writing","research","academic"],
  ["Inline autocomplete","Citation insertion","Journal templates"],
  ["Researchers and students","Long-form writers"],["Speeds drafting","Citation help"],["Academic only focus","Autocomplete can drift"]),
 ("hyperwrite","HyperWrite","writing","Personal writing assistant with autocomplete and rewriting.","Freemium — free tier; Premium $20/mo","4.1",["writing","productivity","copy"],
  ["Flexible autocomplete","Rewrite and expand","Personalized suggestions"],
  ["Daily business writing","Founders"],["Context-aware","Cheap"],["Less known","Variable quality"]),
 ("peppertype","Peppertype","writing","AI content generator with a virtual content assistant.","Paid — from $35/mo","4.2",["writing","marketing","copy"],
  ["50+ content types","Team workspaces","Content rewrite"],
  ["Marketing teams","Agencies"],["Variety of outputs","Team features"],["Merged into PepperType/PEPPER","Quality uneven"]),
 ("ink","INK Editor","writing","SEO-focused writing app with an AI co-writer and keyword planner.","Paid — from $39/mo","4.0",["writing","seo","blog"],
  ["SEO score while writing","AI writer and rewriter","Keyword clustering"],
  ["SEO bloggers","Solopreneurs"],["All-in-one writing+SEO","Good scoring"],["Clunky UI","Steep price"]),
 ("verbix","Verb AI","writing","Lightweight AI editor for rewriting and brainstorming.","Freemium","4.0",["writing","rewrite"],
  ["Rewrite suggestions","Tone control","Browser extension"],
  ["Casual writers","Editors"],["Simple","Free option"],["Basic features"]),
 ("paragraphai","ParagraphAI","writing","Polish, translate, and generate text from a toolbar anywhere.","Freemium — free tier; Pro $10/mo","4.1",["writing","rewrite","translate"],
  ["One-click polish","Translation","Cross-app toolbar"],
  ["Professionals","Multilingual teams"],["Everywhere access","Clean output"],["Not for long docs"]),
 ("loro","Loro","writing","AI writing coach that mimics your favorite authors' style.","Paid — from $8/mo","3.9",["writing","creative","style"],
  ["Style-matching rewrites","Tone coach","Draft feedback"],
  ["Creative writers","Students"],["Unique style angle"],["Niche","Early-stage"]),
 # ---- IMAGE & DESIGN ----
 ("dalle","DALL-E 3","image","OpenAI's image model, integrated into ChatGPT and Bing.","Freemium — via ChatGPT Plus","4.3",["image","generator","art"],
  ["Prompt-to-image in ChatGPT","Inpainting and edits","Natural language understanding"],
  ["Casual creators","Writers wanting visuals"],["Easy access","Good prompt adherence"],["Slow at peak","Watermarked sometimes"]),
 ("stablediffusion","Stable Diffusion","image","Open, customizable image model you can run locally or in the cloud.","Free / open-source","4.5",["image","opensource","generator"],
  ["Fully local and private","Fine-tune your own models","Massive community models"],
  ["Technical creators","Privacy-focused users"],["Free and open","Infinite control"],["Setup friction","Needs GPU"]),
 ("leonardo","Leonardo.Ai","image","Game-art and product-image generator with fine control.","Freemium — free tier; Pro $10/mo","4.5",["image","generator","design"],
  ["Custom model training","Asset-focused presets","API access"],
  ["Game and product designers","Indie creators"],["Great control","Daily free credits"],["Can be slow","Art-style bias"]),
 ("firefly","Adobe Firefly","image","Adobe's commercial-safe image and video model inside Creative Cloud.","Freemium — free tier; via CC","4.4",["image","design","adobe"],
  ["Commercially safe training","Text effects and vectors","Deep Photoshop integration"],
  ["Designers on Creative Cloud","Brands"],["Safe for commercial","Pro quality"],["Locked to Adobe","Credits limit"]),
 ("ideogram","Ideogram","image","Image generator with notably accurate text rendering.","Freemium — free tier; Plus $8/mo","4.4",["image","generator","typography"],
  ["Accurate in-image text","Logos and posters","Fast generations"],
  ["Marketers needing text-in-image","Designers"],["Best text rendering","Cheap"],["Less photoreal"]),
 ("krea","Krea","image","Real-time AI canvas with upscaling and enhancement.","Freemium — free tier; Pro $8/mo","4.3",["image","realtime","enhance"],
  ["Real-time generation","Upscaler and enhancer","Background removal"],
  ["Designers wanting speed","Social creators"],["Real-time feel","Good enhancer"],["Feature churn"]),
 ("playground","Playground AI","image","Graphic-design-meets-image-gen for social and product visuals.","Freemium — free tier; Pro $9/mo","4.2",["image","design","social"],
  ["Image generation + editor","Templates","Logo and mockup tools"],
  ["Social media creators","Small brands"],["Design-friendly","Free tier"],["Less precise prompts"]),
 ("recraft","Recraft","image","Vector and icon generator for consistent brand kits.","Freemium — free tier; Pro $10/mo","4.5",["image","vector","branding"],
  ["AI vector generation","Brand style sets","Icons and illustrations"],
  ["Brand and product designers","Indie hackers"],["Vectors are rare/useful","Style consistency"],["Credit limits"]),
 ("photoroom","Photoroom","image","Remove backgrounds and create product shots in seconds.","Freemium — free tier; Pro $13/mo","4.6",["image","ecommerce","edit"],
  ["One-click background removal","Product shot templates","Batch export"],
  ["Ecommerce sellers","Marketers"],["Best-in-class removal","Fast"],["Pro for batch"]),
 ("removebg","Remove.bg","image","Single-purpose background remover, API-first.","Freemium — free tier; Pro $9/mo","4.5",["image","edit","api"],
  ["Instant cutout","API + plugin ecosystem","Batch via API"],
  ["Developers","Ecommerce"],["Dead simple","API solid"],["One-trick tool"]),
 ("looka","Looka","business","AI logo and brand-kit generator for instant identities.","Paid — one-time from $20","4.3",["logo","branding","business"],
  ["Logo generator","Full brand kit","Social and print assets"],
  ["New businesses","Solopreneurs"],["Fast branding","Affordable"],["Templates can repeat"]),
 ("brandmark","Brandmark","business","AI logo maker with color and font harmony.","Paid — from $25 one-time","4.0",["logo","branding","business"],
  ["Logo + business card","Color palette tools","Batch exports"],
  ["Bootstrappers","Side projects"],["Quick","Cheap"],["Generic sometimes"]),
 ("luma","Luma Dream Machine","image","Image and video model with realistic motion and lighting.","Freemium — free tier; Pro $10/mo","4.5",["image","video","generator"],
  ["Image-to-video","Photoreal stills","Keyframe control"],
  ["Creators wanting motion","Marketers"],["Impressive realism","Easy"],["Queue at peak"]),
 ("kling","Kling AI","video","High-fidelity text-to-video with strong motion coherence.","Freemium — free tier; Pro $10/mo","4.4",["video","generator","image"],
  ["Text-to-video","Image-to-video","Motion brush"],
  ["Creators","Filmmakers"],["Strong motion","Free tier"],["Credits limit","Access queues"]),
 ("topaz","Topaz Photo AI","image","Upscale, denoise, and sharpen photos with AI.","Paid — from $99 one-time","4.5",["image","enhance","photo"],
  ["Upscaler","Denoise and sharpen","Batch processing"],
  ["Photographers","Restorers"],["Pro quality","One-time"],["Desktop only","Heavy"]),
 # ---- VIDEO & AUDIO ----
 ("runway","Runway","video","Creative suite for AI video editing, generation, and motion.","Freemium — free tier; Pro $12/mo","4.5",["video","edit","generator"],
  ["Gen-2 text/image-to-video","Inpainting and rotoscoping","Motion tracking"],
  ["Video creators","Agencies"],["Powerful toolkit","Frequent updates"],["Credit cost","Learning curve"]),
 ("pika","Pika","video","Fun, fast text-to-video with playful effects.","Freemium — free tier; Pro $8/mo","4.3",["video","generator","social"],
  ["Text/image-to-video","Pikaffects","Lip-sync"],
  ["Social creators","Hobbyists"],["Easy and fast","Playful"],["Less cinematic"]),
 ("heygen","HeyGen","video","AI avatar spokespeople and video translation at scale.","Freemium — free tier; Pro $24/mo","4.5",["video","avatar","translate"],
  ["Photo-real avatars","Video translation + lip-sync","Templates"],
  ["Marketers","Course creators"],["Convincing avatars","Localization"],["Avatar uncanny at times"]),
 ("capcut","CapCut","video","TikTok's editor with AI captions, cutout, and effects.","Freemium — free tier; Pro $10/mo","4.6",["video","edit","social"],
  ["Auto captions","Remove background","Trending templates"],
  ["Short-form creators","Solopreneurs"],["Free and capable","Mobile+desktop"],["Watermark on free"]),
 ("opusclip","Opus Clip","video","Turn long videos into viral short clips automatically.","Freemium — free tier; Pro $19/mo","4.4",["video","social","repurpose"],
  ["Auto clip detection","AI b-roll and captions","Keyword highlights"],
  ["YouTubers","Podcasters"],["Great repurposing","Saves hours"],["Hit-or-miss picks"]),
 ("pictory","Pictory","video","Convert scripts and blog posts into branded videos.","Paid — from $19/mo","4.2",["video","script","marketing"],
  ["Script-to-video","Blog-to-video","Auto summaries"],
  ["Content marketers","Agencies"],["Repurpose text fast","Templates"],["Stock-heavy"]),
 ("synthesia","Synthesia","video","Enterprise avatar video platform with 140+ languages.","Paid — from $22/mo","4.5",["video","avatar","enterprise"],
  ["140+ AI avatars","Localization","Templates + LMS"],
  ["L&D teams","Enterprises"],["Scalable training","Multilingual"],["Pricey","Avatar limits"]),
 ("veed","Veed","video","Browser video editor with auto-subtitles and cleanup.","Freemium — free tier; Pro $18/mo","4.3",["video","edit","subtitles"],
  ["Auto subtitles","Background noise remover","Trim and resize"],
  ["Marketers","Educators"],["Easy in-browser","Good subs"],["Watermark free"]),
 ("riverside","Riverside","video","Studio-quality remote recording with AI show notes.","Freemium — free tier; Pro $15/mo","4.5",["video","podcast","record"],
  ["4K local recording","AI transcripts and clips","Magic Audio"],
  ["Podcasters","Interviews"],["Great audio","Separate tracks"],["Pro for exports"]),
 ("fliki","Fliki","video","Turn text into videos with lifelike AI voices.","Freemium — free tier; Pro $21/mo","4.3",["video","voice","script"],
  ["Text-to-video","600+ voices","Stock library"],
  ["Marketers","Educators"],["Voice + video combo","Cheap"],["Stock look"]),
 ("kaiber","Kaiber","video","Animate images and prompts into music-driven video.","Freemium — free tier; Pro $10/mo","4.1",["video","art","music"],
  ["Image-to-video","Spotify-linked motion","Styles"],
  ["Artists","Musicians"],["Artistic","Fun"],["Niche"]),
 ("wisecut","Wisecut","video","Auto-edit talking-head video into punchy shorts.","Freemium — free tier; Pro $10/mo","4.0",["video","edit","social"],
  ["Auto jump cuts","Subtitles and music","Highlights"],
  ["YouTubers","Teachers"],["Hands-free edit"],["Limited control"]),
 ("murf","Murf","video","Studio-quality AI voiceovers for videos and ads.","Freemium — free tier; Pro $19/mo","4.4",["voice","audio","video"],
  ["120+ voices","Voice cloning","Sync to video"],
  ["Video producers","Elearning"],["Natural voices","Easy"],["Cloning gated"]),
 ("otter","Otter.ai","productivity","Live meeting transcription and searchable notes.","Freemium — free tier; Pro $10/mo","4.4",["transcription","meeting","notes"],
  ["Live transcribe","Speaker labels","Search and summary"],
  ["Meeting-heavy pros","Students"],["Reliable captions","Good free"],["Accuracy on accents"]),
 ("fireflies","Fireflies.ai","productivity","Meeting recorder that logs and summarizes every call.","Freemium — free tier; Pro $10/mo","4.3",["meeting","transcription","crm"],
  ["Auto record + summarize","CRM sync","Searchable library"],
  ["Sales teams","Founders"],["CRM integration","Auto notes"],["Storage limits"]),
 ("tactiq","Tactiq","productivity","Real-time meeting notes and AI chat inside calls.","Freemium — free tier; Pro $8/mo","4.1",["meeting","notes","transcript"],
  ["Live transcript","AI chat on call","Export to docs"],
  ["Consultants","Teams"],["Lightweight","Cheap"],["Transcript quality"]),
 # ---- AUTOMATION & WORKFLOW ----
 ("n8n","n8n","automation","Open-source workflow automation with code when you need it.","Freemium — self-host free; Cloud $20/mo","4.6",["automation","opensource","workflow"],
  ["Visual + code nodes","Self-host or cloud","200+ integrations"],
  ["Technical founders","Ops engineers"],["Powerful and free self-host","Flexible"],["Setup needed"]),
 ("ifttt","IFTTT","automation","Dead-simple applets connecting everyday apps and devices.","Freemium — free tier; Pro $3/mo","4.0",["automation","simple","iot"],
  ["One-line applets","Smart-home triggers","Mobile widgets"],
  ["Non-technical users","Smart-home fans"],["Trivial to use","Cheap"],["Limited logic"]),
 ("bardeen","Bardeen","automation","Browser-native automation with AI magic boxes.","Freemium — free tier; Pro $10/mo","4.2",["automation","browser","scrape"],
  ["No-code scraper","GPT in workflows","Playbooks"],
  ["Growth hackers","Researchers"],["Browser-native","Scraping"],["Chrome only"]),
 ("relay","Relay.app","automation","Human-in-the-loop automation with AI steps.","Freemium — free tier; Pro $13/mo","4.3",["automation","workflow","ai"],
  ["AI steps","Approvals","Templates"],
  ["Ops teams","SMBs"],["Human approvals","Clean UI"],["Smaller catalog"]),
 ("pipedream","Pipedream","automation","Developer automation with code and 2,000+ APIs.","Freemium — free tier; Pro $20/mo","4.4",["automation","api","developer"],
  ["Serverless workflows","Prebuilt API actions","Event sources"],
  ["Developers","Backend teams"],["Code + no-code","Fast"],["Dev leaning"]),
 ("dify","Dify","automation","Open-source LLM app builder and agent workflows.","Freemium — self-host free; Cloud $59/mo","4.5",["automation","llm","agent"],
  ["Build AI apps visually","RAG pipelines","Agent workflows"],
  ["AI builders","Startups"],["Open and capable","RAG built-in"],["Technical setup"]),
 ("gumloop","Gumloop","automation","Drag-and-drop AI automation for business workflows.","Freemium — free tier; Pro $29/mo","4.2",["automation","ai","workflow"],
  ["Visual AI flows","Browser nodes","Subflows"],
  ["Ops and GTM","Founders"],["No-code AI","Intuitive"],["Credits limit"]),
 ("tray","Tray.io","automation","Enterprise iPaaS with a flexible visual builder.","Paid — custom","4.1",["automation","enterprise","ipaas"],
  ["General automation","Citizen + pro modes","Connectors"],
  ["Enterprises","RevOps"],["Scales well"],["Custom pricing"]),
 ("beamlabs","Beam AI","automation","Autonomous agents that run repetitive back-office work.","Paid — custom","4.0",["automation","agent","rpa"],
  ["Autonomous agents","Process mining","Handoff to human"],
  ["Operations teams","Finance"],["Agentic approach"],["Early/enterprise"]),
 ("xembly","Xembly","automation","AI chief-of-staff that runs meetings and tasks.","Paid — custom","3.9",["automation","meeting","tasks"],
  ["Auto meeting notes","Task tracking","Calendar control"],
  ["Exec teams","Managers"],["Saves coordination"],["Enterprise focus"]),
 # ---- PRODUCTIVITY & RESEARCH ----
 ("mem","Mem","productivity","Self-organizing notes with AI that writes and finds.","Freemium — free tier; Pro $8/mo","4.1",["notes","productivity","ai"],
  ["Auto-organized notes","AI search","Smart write"],
  ["Note-takers","Researchers"],["No folders needed","Fast"],["Sync limits"]),
 ("taskade","Taskade","productivity","AI workspace for tasks, docs, and agents.","Freemium — free tier; Pro $8/mo","4.3",["tasks","productivity","ai"],
  ["Tasks + docs + chat","AI agents","Templates"],
  ["Remote teams","Founders"],["All-in-one","Cheap"],["Jack-of-all"]),
 ("motion","Motion","productivity","AI calendar that auto-schedules your tasks and meetings.","Paid — from $19/mo","4.2",["calendar","productivity","schedule"],
  ["Auto-scheduling","Project + tasks","Prioritization"],
  ["Busy founders","Managers"],["Saves planning","Smart"],["Pricey","Rigid"]),
 ("reclaim","Reclaim","productivity","AI time blocking that defends deep work in your calendar.","Freemium — free tier; Pro $8/mo","4.3",["calendar","productivity","focus"],
  ["Smart time blocking","Habits and tasks","1:1 defends"],
  ["Knowledge workers","Teams"],["Protects focus","Google-native"],["Google only"]),
 ("superhuman","Superhuman","productivity","AI-accelerated email with snappy shortcuts.","Paid — from $20/mo","4.4",["email","productivity","inbox"],
  ["Split-inbox","Write with AI","Speed shortcuts"],
  ["Inbox-zero pros","Execs"],["Blazing fast","Great UX"],["Pricey","Gmail/Outlook"]),
 ("clickup","ClickUp","productivity","All-in-one project and docs with AI assistant.","Freemium — free tier; Pro $7/mo","4.2",["pm","productivity","docs"],
  ["Tasks, docs, whiteboards","AI writer","Automations"],
  ["Teams","Agencies"],["Very full-featured","Free tier"],["Overwhelming UI"]),
 ("todoist","Todoist","productivity","Clean task manager with natural-language AI.","Freemium — free tier; Pro $4/mo","4.4",["tasks","productivity","gtd"],
  ["Quick capture","AI prioritization","Cross-platform"],
  ["GTD practitioners","Everyone"],["Simple and reliable","Cheap"],["No docs"]),
 ("raycast","Raycast","productivity","Launcher with AI commands, snippets, and dev tools.","Freemium — free tier; Pro $8/mo","4.7",["launcher","productivity","dev"],
  ["Instant commands","AI chat + quicklinks","Extensions"],
  ["Developers","Power users"],["Huge speedup","Extensible"],["macOS only"]),
 ("miro","Miro","productivity","Infinite whiteboard with AI diagramming and synthesis.","Freemium — free tier; Pro $8/mo","4.3",["whiteboard","productivity","brainstorm"],
  ["Infinite canvas","AI summarize + diagram","Templates"],
  ["Teams","Designers"],["Visual colllab","Good free"],["Cluttered boards"]),
 ("whimsical","Whimsical","productivity","Fast flowcharts, wireframes, and docs with AI.","Freemium — free tier; Pro $10/mo","4.4",["diagram","productivity","docs"],
  ["Flows and wireframes","AI docs","Mind maps"],
  ["Product teams","Founders"],["Fast and clean","AI docs"],["Boards limited"]),
 ("chatpdf","ChatPDF","productivity","Chat with any PDF to extract answers fast.","Freemium — free tier; Pro $5/mo","4.3",["pdf","research","chat"],
  ["Document chat","Citations to pages","Multi-file"],
  ["Researchers","Students"],["Quick understanding","Cheap"],["Large docs limit"]),
 ("wiseone","Wiseone","productivity","AI reading assistant that explains and cross-checks.","Freemium — free tier; Pro $10/mo","4.1",["reading","research","ai"],
  ["Simplify articles","Cross-check claims","Ask anything"],
  ["Readers","Researchers"],["Browser-native"],["Niche"]),
 ("consensus","Consensus","productivity","AI search over peer-reviewed research papers.","Freemium — free tier; Pro $7/mo","4.3",["research","academic","search"],
  ["Study summaries","Consensus meters","Citations"],
  ["Researchers","Students"],["Evidence-based","Fast"],["Narrow scope"]),
 ("scite","Scite","productivity","Smart citations that show whether papers support claims.","Freemium — free tier; Pro $10/mo","4.2",["research","academic","citations"],
  ["Smart citations","Assistant search","Reference manager"],
  ["Academics","Writers"],["Novel citation view"],["Research focus"]),
 ("elicit","Elicit","productivity","AI literature review that extracts data from papers.","Freemium — free tier; Pro $10/mo","4.3",["research","academic","review"],
  ["Literature review","Data extraction","Summaries"],
  ["Researchers","Students"],["Saves review time"],["Academic only"]),
 # ---- CODING & BUILD ----
 ("copilot","GitHub Copilot","coding","Inline AI pair programmer inside your editor.","Paid — from $10/mo","4.4",["coding","pair","editor"],
  ["Inline completions","Chat in IDE","Multi-file edits"],
  ["Developers","Teams"],["Proven speedup","Everywhere"],["Can suggest bugs"]),
 ("claudecode","Claude Code","coding","Agentic CLI that plans, edits, and runs your codebase.","Paid — via Claude Pro/Max","4.6",["coding","agent","cli"],
  ["Repo-wide edits","Terminal agent","Tool use"],
  ["Developers","Power users"],["Strong reasoning","Autonomous"],["Needs oversight"]),
 ("v0","v0.dev","coding","Generate UI components and apps from prompts.","Freemium — free tier; Pro $20/mo","4.4",["coding","ui","frontend"],
  ["Prompt-to-UI","React + Tailwind","Iterative chat"],
  ["Frontend devs","Founders"],["Fast prototypes","Clean code"],["Frontend only"]),
 ("replit","Replit","coding","Cloud IDE with an AI agent that builds apps end to end.","Freemium — free tier; Core $20/mo","4.3",["coding","ide","agent"],
  ["Agent build","Cloud IDE","Deploy in-app"],
  ["Beginners","Founders"],["Zero setup","Deployable"],["Limited compute"]),
 ("bolt","Bolt.new","coding","Prompt-to-fullstack-app in the browser, edit live.","Freemium — free tier; Pro $20/mo","4.4",["coding","fullstack","ui"],
  ["Fullstack gen","Live editor","One-click deploy"],
  ["Founders","Prototypers"],["Instant apps","No setup"],["Token use"]),
 ("lovable","Lovable","coding","Chat your way to full-stack web apps with auth and DB.","Freemium — free tier; Pro $20/mo","4.5",["coding","fullstack","nocode"],
  ["Chat-to-app","Supabase backend","Deploy"],
  ["Non-dev founders","Builders"],["Ships real apps","Fast"],["Backend ceiling"]),
 ("windsurf","Windsurf","coding","AI-native editor with Cascade agent flows.","Freemium — free tier; Pro $15/mo","4.4",["coding","editor","agent"],
  ["Cascade agent","Multi-file edits","Cmd+K"],
  ["Developers","Teams"],["Agentic edits","Fast"],["Pro for limits"]),
 ("tabnine","Tabnine","coding","Privacy-first AI completions, self-hostable.","Freemium — free tier; Pro $12/mo","4.1",["coding","pair","privacy"],
  ["Local/private models","Whole-line completions","Enterprise"],
  ["Enterprise devs","Privacy buyers"],["Private option","Cheap"],["Less capable"]),
 ("codeium","Codeium","coding","Free AI autocomplete and chat across editors.","Freemium — free tier; Pro $15/mo","4.4",["coding","pair","free"],
  ["Fast completions","Chat + search","Many IDEs"],
  ["Developers","Students"],["Free and solid","Broad support"],["Not agentic"]),
 ("sourcegraph","Sourcegraph Cody","coding","Codebase-aware AI using your whole repo as context.","Freemium — free tier; Pro $9/mo","4.2",["coding","rag","editor"],
  ["Repo-aware chat","Contextual edits","Many IDEs"],
  ["Large codebases","Teams"],["Knows your code","Good free"],["Setup for big repos"]),
 ("cline","Cline","coding","Open-source autonomous coding agent in VS Code.","Free / open-source","4.5",["coding","agent","opensource"],
  ["Plan + act modes","Tool use in terminal","File edits"],
  ["Developers","OSS fans"],["Open and capable","Transparent"],["Early maturity"]),
 ("devin","Devin","coding","Autonomous AI software engineer for whole tasks.","Paid — from $500/mo","4.0",["coding","agent","enterprise"],
  ["End-to-end tasks","PRs from issues","Shell + browser"],
  ["Eng teams","Startups"],["Truly autonomous"],["Pricey","Needs review"]),
 ("sweep","Sweep","coding","Bot that turns issues into code PRs.","Freemium — free tier; Pro $20/mo","3.9",["coding","bot","pr"],
  ["Issue-to-PR","Repo-aware","GitHub native"],
  ["Maintainers","Teams"],["Auto PRs"],["Quality varies"]),
 ("aider","Aider","coding","Terminal pair programmer that edits your repo via git.","Free / open-source","4.5",["coding","cli","opensource"],
  ["Repo edits via chat","Git diffs","Many models"],
  ["Developers","CLI fans"],["Powerful + free","Transparent"],["Terminal only"]),
 ("vanna","Vanna","coding","Text-to-SQL with verified, self-learning queries.","Freemium — free tier; Pro $19/mo","4.1",["coding","sql","data"],
  ["NL to SQL","Self-improving","Connectors"],
  ["Analysts","Data teams"],["Democratizes SQL"],["Setup per DB"]),
 ("pythagora","Pythagora","coding","Generate Node.js apps from natural language specs.","Free / open-source","4.0",["coding","fullstack","agent"],
  ["Spec-to-app","Auto testing","Debugging"],
  ["Founders","Students"],["No-code-ish"],["Node only"]),
 # ---- MARKETING & SEO ----
 ("semrush","Semrush","marketing","All-in-one SEO, PPC, and competitive research suite.","Paid — from $119/mo","4.5",["seo","research","marketing"],
  ["Keyword + position tracking","Site audit","Competitor gaps"],
  ["SEO pros","Agencies"],["Comprehensive","Reliable"],["Expensive"]),
 ("ahrefs","Ahrefs","marketing","Backlink and SEO analytics trusted by pros.","Paid — from $99/mo","4.6",["seo","backlinks","marketing"],
  ["Site explorer","Content explorer","Rank tracker"],
  ["SEO teams","Marketers"],["Best backlinks","Deep data"],["Pricey"]),
 ("rankmath","Rank Math","marketing","WordPress SEO plugin with AI content and schema.","Freemium — free tier; Pro $59/yr","4.5",["seo","wordpress","plugin"],
  ["On-page SEO","Schema generator","AI suggestions"],
  ["WordPress site owners","Bloggers"],["Powerful free","WP-native"],["WP only"]),
 ("ococa","Ocoya","marketing","AI social content and scheduling in one.","Freemium — free tier; Pro $15/mo","4.2",["social","marketing","copy"],
  ["AI post generator","Scheduling","Analytics"],
  ["Solopreneurs","Agencies"],["Content + schedule","Cheap"],["Design basic"]),
 ("predis","Predis.ai","marketing","AI social posts and competitor analysis.","Freemium — free tier; Pro $24/mo","4.3",["social","marketing","design"],
  ["Carousel + reel maker","Idea labs","Competitor insights"],
  ["Social managers","Brands"],["Visual posts","Easy"],["Niche"]),
 ("adcreative","AdCreative.ai","marketing","Generate scroll-stopping ad creatives with scores.","Paid — from $21/mo","4.1",["ads","marketing","design"],
  ["Ad creatives","Performance scores","Competitor insights"],
  ["Performance marketers","Ecom"],["Fast variants","Scored"],["Credit limits"]),
 ("mailchimp","Mailchimp","marketing","Email marketing with AI content and journeys.","Freemium — free tier; Essentials $13/mo","4.2",["email","marketing","crm"],
  ["Email builder","Automations","AI content"],
  ["Small businesses","Creators"],["Familiar","Free tier"],["Price creep"]),
 ("brevo","Brevo","marketing","Email + SMS marketing with a free tier.","Freemium — free tier; Starter $9/mo","4.3",["email","marketing","sms"],
  ["Email + SMS","CRM lite","Automations"],
  ["SMBs","Startups"],["Generous free","Multi-channel"],["Deliverability tiers"]),
 ("instantly","Instantly.ai","marketing","Cold email at scale with AI warmup.","Paid — from $30/mo","4.2",["email","outreach","marketing"],
  ["Unlimited sending","AI warmup","Lead finder"],
  ["Agencies","Outreach teams"],["Scale","Deliverability"],["Spam risk if abused"]),
 ("smartlead","Smartlead","marketing","Cold outreach with unlimited warmup and AI.","Paid — from $33/mo","4.1",["email","outreach","marketing"],
  ["Master inbox","Warmup","API"],
  ["Outreach pros","Agencies"],["Unlimited warmup","Solid"],["UI clunky"]),
 ("taplio","Taplio","marketing","LinkedIn growth with AI posts and engagement.","Paid — from $39/mo","4.2",["linkedin","social","marketing"],
  ["AI post drafts","Lead discovery","Analytics"],
  ["LinkedIn creators","B2B"],["Growth-focused","Good scraping"],["LinkedIn only"]),
 ("postiz","Postiz","marketing","Open-source social media scheduling and AI.","Freemium — self-host free; Pro $20/mo","4.3",["social","opensource","marketing"],
  ["Multi-channel scheduling","AI drafts","Analytics"],
  ["Solopreneurs","Teams"],["Open + cheap","Clean"],["Smaller catalog"]),
 ("hypefury","Hypefury","marketing","Twitter/X and LinkedIn growth automation.","Paid — from $15/mo","4.2",["social","marketing","growth"],
  ["Auto-retweet threads","Lead magnets","Scheduling"],
  ["Solopreneurs","Creators"],["Great for threads","Simple"],["X-heavy"]),
 ("character","Character.ai","productivity","Chat with personas and build your own bots.","Freemium — free tier; c.ai+ $10/mo","4.3",["chatbot","roleplay","fun"],
  ["Persona bots","Create your own","Group chat"],
  ["Casual users","Hobbyists"],["Fun + free","Creative"],["Not business"]),
 ("poe","Poe","productivity","One inbox for many AI bots (Claude, GPT, others).","Freemium — free tier; Pro $20/mo","4.3",["chatbot","aggregator","ai"],
  ["Many models in one","Bot creator","Fast switching"],
  ["AI power users","Curious minds"],["Model choice","Cheap"],["No own models"]),
 ("gamma","Gamma","productivity","AI decks, docs, and sites from a prompt.","Freemium — free tier; Pro $8/mo","4.4",["presentations","productivity","design"],
  ["Prompt-to-deck","Live websites","Templates"],
  ["Founders","Educators"],["Fast decks","Polished"],["Less custom"]),
 ("notionai","Notion AI","productivity","Writing, Q&A, and search inside your Notion workspace.","Paid — add-on $8/user","4.3",["notes","ai","productivity"],
  ["AI writer in docs","Q&A across workspace","Summarize"],
  ["Notion users","Teams"],["Context-aware","Native"],["Add-on cost"]),
 ("memair","Memair","productivity","Personal AI memory that learns from your life logs.","Paid — from $9/mo","3.8",["memory","productivity","personal"],
  ["Personal memory","Q&A your history","Integrations"],
  ["Quantified-self fans","Researchers"],["Unique concept"],["Niche"]),
 # ---- BUSINESS & FINANCE ----
 ("quickbooks","QuickBooks","business","Full accounting with AI categorization and insights.","Paid — from $30/mo","4.2",["accounting","finance","business"],
  ["Auto-categorization","Invoicing","Reports"],
  ["Small businesses","Freelancers"],["Industry standard","Strong"],["Pricey","Clunky"]),
 ("freshbooks","FreshBooks","business","Invoicing and expense tracking for service businesses.","Paid — from $17/mo","4.1",["invoicing","finance","business"],
  ["Invoicing","Time tracking","Expense capture"],
  ["Freelancers","Agencies"],["Simple billing","Mobile"],["Limited accounting"]),
 ("wave","Wave","business","Free accounting and invoicing for tiny businesses.","Freemium — free accounting; Payments fee","4.0",["accounting","free","business"],
  ["Free accounting","Invoicing","Payments"],
  ["Micro-businesses","Solopreneurs"],["Free core","Easy"],["Paid add-ons"]),
 ("ramp","Ramp","business","Corporate cards with AI spend controls and savings.","Free — card program","4.5",["finance","cards","business"],
  ["Auto receipts","Spend insights","No-fee cards"],
  ["Startups","Finance teams"],["Saves real money","Free"],["US only"]),
 ("mercury","Mercury","business","Banking for startups with automation and APIs.","Free — banking","4.4",["banking","finance","business"],
  ["Startup banking","API + automations","Vaults"],
  ["Startups","Founders"],["Great UX","API"],["US/entities only"]),
 ("float","Float","business","Cash-flow forecasting built on your accounting data.","Paid — from $49/mo","4.2",["finance","cashflow","business"],
  ["Cash forecasting","Budget vs actual","Syncs accounting"],
  ["Finance leads","Agencies"],["Clear forecasts"],["Accounting required"]),
 ("durable","Durable","business","AI builds a website, CRM, and invoices in minutes.","Paid — from $12/mo","4.1",["website","business","crm"],
  ["AI website builder","Invoicing + CRM","Ad copy"],
  ["New businesses","Solopreneurs"],["Instant launch","Cheap"],["Template look"]),
 ("mixo","Mixo","business","Launch a startup site and validate an idea fast.","Paid — from $9/mo","4.0",["website","business","launch"],
  ["AI landing pages","Waitlist + email","Idea validation"],
  ["Founders","Indie hackers"],["Fast validation","Simple"],["Limited"]),
 ("stitch","Stitch","business","AI generates UI design from prompts and images.","Freemium — free tier; Pro $10/mo","4.2",["design","ui","business"],
  ["Prompt-to-UI","Image-to-design","Export to code"],
  ["Product teams","Founders"],["Google-backed","Fast"],["New/early"]),
 ("doola","Doola","business","Formation, bookkeeping, and banking for US startups.","Paid — from $39/mo","4.1",["formation","finance","business"],
  ["LLC/Corp formation","Bookkeeping","US banking"],
  ["Non-US founders","Startups"],["Full-stack setup"],["US-focused"]),
 ("indy","Indy","business","All-in-one freelance suite: CRM, contracts, invoices.","Freemium — free tier; Pro $9/mo","4.0",["freelance","business","crm"],
  ["Proposals + contracts","Time tracking","Invoicing"],
  ["Freelancers","Consultants"],["Covers everything","Cheap"],["Less deep"]),
 ("bonsai","Bonsai","business","Freelance OS: proposals, contracts, and taxes.","Paid — from $17/mo","4.2",["freelance","business","crm"],
  ["Proposals","Contracts + e-sign","Tax estimates"],
  ["Freelancers","Agencies"],["Polished suite","Reliable"],["Pricey"]),
 ("harvest","Harvest","business","Time tracking and invoicing that feeds profitability.","Freemium — free tier; Pro $11/mo","4.4",["time","invoicing","business"],
  ["Time tracking","Invoicing","Reports"],
  ["Agencies","Consultants"],["Simple + solid","Integrations"],["No full accounting"]),
 ("expensify","Expensify","business","Receipt scanning and expense approvals on autopilot.","Freemium — free tier; Pro $5/mo","4.1",["expenses","finance","business"],
  ["SmartScan receipts","Approval flows","Reimbursement"],
  ["Teams","Finance"],["Receipts easy","Integrations"],["UI dated"]),
]

# tags homogenized to lowercase slugs already
TEMPLATE = """slug: {slug}
name: "{name}"
category: {category}
summary: "{summary}"
pricing: "{pricing}"
affiliate: ""
rating: {rating}
tags: [{tags}]
features:
{features}
best_for:
{best_for}
pros:
{pros}
cons:
{cons}
"""

def lit(items):
    return "\n".join(f"  - {x}" for x in items)

def main():
    existing = {f[:-5] for f in os.listdir(OUT) if f.endswith(".yaml")}
    added = 0
    for (slug, name, cat, summary, pricing, rating, tags, feat, best, pros, cons) in T:
        # force rewrite every row so templated changes apply
        text = TEMPLATE.format(
            slug=slug, name=name, category=cat, summary=summary, pricing=pricing,
            rating=rating, tags=", ".join(tags), features=lit(feat),
            best_for=lit(best), pros=lit(pros), cons=lit(cons),
        )
        with open(os.path.join(OUT, f"{slug}.yaml"), "w", encoding="utf-8") as f:
            f.write(text)
        added += 1
    print(f"Wrote {added} new tool YAML files. Total in data/tools/: {len(existing)+added}")

if __name__ == "__main__":
    main()
